/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlyhoa.array;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {
    private List<array> list= new ArrayList<>();
    private DefaultTableModel model;
     private DefaultTableModel model1;
    private String [] columHeaders= new String[] {"Tên Hoa","Mã Hoa ","Màu Hoa","Loại Hoa","Số Lượng","Số Cánh Hoa","Số Hoa Con"};
    private String [] columHeaders1= new String[] {"Tên Hoa","Mã Hoa ","Màu Hoa","Loại Hoa","Số Lượng","Số Cánh Hoa","Số Hoa Con","thời gian"};
    private String loaihoakho;
    
    /**
     * Creates new form NewJFrame
     */
    public void thu(){
        String b0=theten.getText();
         String b1=thema.getText();
          String b2=themau.getText();
           String b3=theloai.getSelectedItem().toString();
            String b4=thesoluong.getText();
            int soluong=Integer.parseInt(b4);
    DefaultTableModel model_table = (DefaultTableModel) table_1.getModel();
    for (int i = 0; i < model_table.getRowCount(); i++) {
    String a0 = model_table.getValueAt(i, 0) + "";
     String a1 = model_table.getValueAt(i, 1) + "";
      String a2 = model_table.getValueAt(i, 2) + "";
       String a3 = model_table.getValueAt(i, 3) + "";
        String a4 = model_table.getValueAt(i, 4) + "";
        int soluongin=Integer.parseInt(a4);
    if(a0.equals(b0)||a1.equals(b1)||a2.equals(b2)||a3.equals(b3)){
     table_1.setValueAt(String.valueOf(soluong+soluongin), i, 4);
    }
    
    //model_table.removeRow(i);							
    }
    }
    public void thongbao(){
        String b1 =theten.getText();
         String b2 =thema.getText();
          String b3 =themau.getText();
           String b4 =thesocanhhoa.getText();
            String b5 =thesohoacon.getText();
              String b6 =thesoluong.getText();
              
              try{
                  Integer.parseInt(b4);
                   Integer.parseInt(b5);
                    Integer.parseInt(b6);
                  
                  
              }
              catch(Exception e){
                  JOptionPane.showMessageDialog(rootPane,"Ban can nhap so"); 
                  
              }
       
       if("".equals(b1)||"".equals(b2)||"".equals(b3)||"".equals(b6)){
            JOptionPane.showMessageDialog(rootPane,"Ban nhap thieu du lieu");
       }
       if("Hoa đơn".equals(loaihoakho)){
           if("".equals(b5))
                JOptionPane.showMessageDialog(rootPane,"Ban nhap thieu so canh hoa");
       }
       else
       if("Hoa Đa".equals(loaihoakho)){
           if("".equals(b4))
                JOptionPane.showMessageDialog(rootPane,"Ban nhap thieu so hoa con");
       }
       
       
    }
    public void xoa(){
        theten.setText(null);thema.setText(null);themau.setText(null);
        thesoluong.setText(null);thesocanhhoa.setText(null);
        thesohoacon.setText(null);theloai.setSelectedIndex(0);
    }
    public NewJFrame() {
        initComponents();
        viewnhapp.setVisible(false);
        viewbang.setVisible(false);
        viewxuatt.setVisible(false);
        viewbangnhap.setVisible(false);
        viewbangxuat.setVisible(false);
        intable();

    }
    private void intable(){
        model =new DefaultTableModel();
        model.setColumnIdentifiers(columHeaders);
        table_1.setModel(model);
        model1 =new DefaultTableModel();
        model1.setColumnIdentifiers(columHeaders1);
        phieunhap.setModel(model1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewnhapp = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        theten = new javax.swing.JTextField();
        thema = new javax.swing.JTextField();
        themau = new javax.swing.JTextField();
        thesoluong = new javax.swing.JTextField();
        theloai = new javax.swing.JComboBox<>();
        thesocanhhoa = new javax.swing.JTextField();
        thesohoacon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewxuatt = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        viewbang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        viewbangnhap = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        phieunhap = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        viewbangxuat = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        phieuxuat = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        nutxuatsp = new javax.swing.JLabel();
        nutannhap = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nutphieunhap = new javax.swing.JLabel();
        nutphieuxuat = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        viewnhapp.setForeground(new java.awt.Color(153, 255, 153));

        jToggleButton1.setText("nhap");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        theten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thetenActionPerformed(evt);
            }
        });

        theloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoa đơn", "Hoa đa" }));
        theloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theloaiActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên Hoa Khô");

        jLabel2.setText("Mã Hoa");

        jLabel3.setText("Màu hoa");

        jLabel4.setText("Loại Hoa");

        jLabel5.setText("Số Cánh Hoa");

        jLabel6.setText("Số Hoa Con");

        jLabel7.setText("Số Lượng Hoa");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setText("NHẬP HÀNG");

        javax.swing.GroupLayout viewnhappLayout = new javax.swing.GroupLayout(viewnhapp);
        viewnhapp.setLayout(viewnhappLayout);
        viewnhappLayout.setHorizontalGroup(
            viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewnhappLayout.createSequentialGroup()
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewnhappLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(viewnhappLayout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(86, 86, 86))
                            .addGroup(viewnhappLayout.createSequentialGroup()
                                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thema, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(theten, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(themau, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(theloai, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thesocanhhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thesohoacon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(viewnhappLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel10)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        viewnhappLayout.setVerticalGroup(
            viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewnhappLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(themau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thesocanhhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thesohoacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewnhappLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Chọn Sản phẩm cần xuât");

        jLabel9.setText("Số Lượng");

        jButton1.setText("xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setText("XUẤT HÀNG");

        javax.swing.GroupLayout viewxuattLayout = new javax.swing.GroupLayout(viewxuatt);
        viewxuatt.setLayout(viewxuattLayout);
        viewxuattLayout.setHorizontalGroup(
            viewxuattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewxuattLayout.createSequentialGroup()
                .addGroup(viewxuattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewxuattLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewxuattLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel11))
                    .addGroup(viewxuattLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1))
                    .addGroup(viewxuattLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        viewxuattLayout.setVerticalGroup(
            viewxuattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewxuattLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(viewxuattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ten", "ma", "mau", "loại", "so luong", "so canh hoa", "so hoa con"
            }
        ));
        jScrollPane1.setViewportView(table_1);

        javax.swing.GroupLayout viewbangLayout = new javax.swing.GroupLayout(viewbang);
        viewbang.setLayout(viewbangLayout);
        viewbangLayout.setHorizontalGroup(
            viewbangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewbangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
        );
        viewbangLayout.setVerticalGroup(
            viewbangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1777, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2468, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        phieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên Hoa", "Mã Hoa", "Màu hoa", "Loại Hoa", "Số cánh hoa", "Số hoa con", "Số luọng", "Thời Gian"
            }
        ));
        jScrollPane5.setViewportView(phieunhap);

        jLabel14.setText("Phiếu Nhập");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout viewbangnhapLayout = new javax.swing.GroupLayout(viewbangnhap);
        viewbangnhap.setLayout(viewbangnhapLayout);
        viewbangnhapLayout.setHorizontalGroup(
            viewbangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(viewbangnhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewbangnhapLayout.setVerticalGroup(
            viewbangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewbangnhapLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        phieuxuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên Hoa", "Mã Hoa", "Màu hoa", "Loại Hoa", "Số cánh hoa", "Số hoa con", "Số luọng", "Thời Gian"
            }
        ));
        jScrollPane6.setViewportView(phieuxuat);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        jLabel15.setText("Phiếu Xuất");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout viewbangxuatLayout = new javax.swing.GroupLayout(viewbangxuat);
        viewbangxuat.setLayout(viewbangxuatLayout);
        viewbangxuatLayout.setHorizontalGroup(
            viewbangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbangxuatLayout.createSequentialGroup()
                .addGroup(viewbangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewbangxuatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(viewbangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewbangxuatLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        viewbangxuatLayout.setVerticalGroup(
            viewbangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewbangxuatLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(viewbangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewbangxuatLayout.createSequentialGroup()
                    .addGap(207, 207, 207)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(viewnhapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewxuatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewbang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewbangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewbangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1066, 1066, 1066)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 259, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(801, 801, 801))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewbangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewbangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewbang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewxuatt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewnhapp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        nutxuatsp.setForeground(new java.awt.Color(255, 255, 255));
        nutxuatsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-export-30.png"))); // NOI18N
        nutxuatsp.setText("Xuất Sản Phẩm");
        nutxuatsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nutxuatspMouseClicked(evt);
            }
        });

        nutannhap.setForeground(new java.awt.Color(255, 255, 255));
        nutannhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/import.png"))); // NOI18N
        nutannhap.setText("Nhập Sản Phẩm");
        nutannhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nutannhapMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        nutphieunhap.setText("jLabel16");
        nutphieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nutphieunhapMouseClicked(evt);
            }
        });

        nutphieuxuat.setText("Phiếu Xuất");
        nutphieuxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nutphieuxuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nutannhap, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nutxuatsp)
                        .addGap(30, 30, 30)
                        .addComponent(nutphieunhap)
                        .addGap(45, 45, 45)
                        .addComponent(nutphieuxuat)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nutannhap)
                            .addComponent(nutxuatsp)
                            .addComponent(nutphieunhap)
                            .addComponent(nutphieuxuat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quản Lý Hoa Khô");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1312, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nutannhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nutannhapMouseClicked
        viewnhapp.setVisible(true);
        viewbang.setVisible(true);
        viewxuatt.setVisible(false);
    }//GEN-LAST:event_nutannhapMouseClicked

    private void nutxuatspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nutxuatspMouseClicked
        viewxuatt.setVisible(true);
        viewbang.setVisible(true);
        viewnhapp.setVisible(false);
    }//GEN-LAST:event_nutxuatspMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int thesl=Integer. parseInt(jTextField2.getText()); 

        DefaultTableModel model_table = (DefaultTableModel) table_1.getModel();
        
        for (int i = 0; i < model_table.getRowCount(); i++) {
         String d1 = model_table.getValueAt(i, 1) + "";
         String sl=model_table.getValueAt(i, 4) + "";
         int sluong=Integer. parseInt(sl); 
       
        int tb=table_1.getSelectedRow();
        String a=(String.valueOf(table_1.getValueAt(tb,0)));
        String a1=(String.valueOf(table_1.getValueAt(tb,1)));
        String a2=(String.valueOf(table_1.getValueAt(tb,2)));
        String a3=(String.valueOf(table_1.getValueAt(tb,3)));
        String a4=(String.valueOf(table_1.getValueAt(tb,4)));
        String a5=(String.valueOf(table_1.getValueAt(tb,5)));
        String a6=(String.valueOf(table_1.getValueAt(tb,6)));
        int soluong= Integer. parseInt(a4);
        if(thesl>soluong){
            JOptionPane.showMessageDialog(rootPane,"So luong xuat khong đu");
        }
        else
        {
            table_1.setValueAt(String.valueOf(soluong-thesl), tb, 4);
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void theloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theloaiActionPerformed
        loaihoakho= theloai.getSelectedItem().toString();
        if("Hoa đơn".equals(loaihoakho)){
            thesohoacon.setText("0");
        }
        else
        if("Hoa đa".equals(loaihoakho)){
            thesocanhhoa.setText("0");
        }
    }//GEN-LAST:event_theloaiActionPerformed

    private void thetenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thetenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thetenActionPerformed

    private void hamnhapdl(){
        thongbao();
        DefaultTableModel model_table = (DefaultTableModel) table_1.getModel();
            DefaultTableModel model_table1 = (DefaultTableModel) phieuxuat.getModel();
             int bien=0;
            String c1 =theten.getText();
            String c2 =thema.getText();
            String c3 =themau.getText();
            String c4 =thesocanhhoa.getText();
            String c5 =thesohoacon.getText();
            String c6 =thesoluong.getText();
              if("".equals(c1)||"".equals(c2)||"".equals(c3)||"".equals(c6)){
                  bien=1;
            
       }   
            if(bien==0){  
            array hoa =new array();
            hoa.setTen(theten.getText());
            hoa.setMahoa(thema.getText());
            hoa.setMau(themau.getText());
            hoa.setSocanhhoa(thesocanhhoa.getText());
            hoa.setSohoacon(thesohoacon.getText());
            hoa.setSoluong(thesoluong.getText());
            list.add(hoa);
            model.setRowCount(0);
            model1.setRowCount(0);
            if("Hoa đơn".equals(loaihoakho))
            list.forEach(item->{
                model.addRow(new Object[]{item.getTen(),item.getMahoa(),item.getMau(),"hoa don",item.getSoluong(),item.getSocanhhoa(),item.getSohoacon()});
                model1.addRow(new Object[]{item.getTen(),item.getMahoa(),item.getMau(),"hoa don",item.getSoluong(),item.getSocanhhoa(),item.getSohoacon(),java.time.LocalDateTime.now()});
            
            });
            else
            if("Hoa đa".equals(loaihoakho))
            list.forEach(item->{
                model.addRow(new Object[]{item.getTen(),item.getMahoa(),item.getMau(),"hoa da",item.getSoluong(),item.getSocanhhoa(),item.getSohoacon()});
             model1.addRow(new Object[]{item.getTen(),item.getMahoa(),item.getMau(),"hoa da",item.getSoluong(),item.getSocanhhoa(),item.getSohoacon(),java.time.LocalDateTime.now()});
            
            });
             model.fireTableDataChanged();
             model1.fireTableDataChanged();
            }
            

        xoa();
        thesocanhhoa.setText(null);
        thesohoacon.setText(null);
    }
    String mangtam[][] =new String [1000][1000];
   
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
            DefaultTableModel model_table = (DefaultTableModel) table_1.getModel();
            DefaultTableModel model_table1 = (DefaultTableModel) phieuxuat.getModel();
            
             int k=0;
             int z = 0;
            for (int i = 0; i < model_table.getRowCount(); i++) {
               
                String a0 = model_table.getValueAt(i, 0) + "";
                String a1 = model_table.getValueAt(i, 1) + "";
                String a2 = model_table.getValueAt(i, 2) + "";
                String a3 = model_table.getValueAt(i, 3) + "";
        	String a4 = model_table.getValueAt(i, 4) + "";
         	String a5 = model_table.getValueAt(i, 5) + "";
          	String a6 = model_table.getValueAt(i, 6) + "";
           
                mangtam[i][0]=a0;
                mangtam[i][1]=a1;
                mangtam[i][2]=a2;
                mangtam[i][3]=a3;
                mangtam[i][4]=a4;
                mangtam[i][5]=a5;
                mangtam[i][6]=a6;
                
                   
    }
       String m0=theten.getText();
       String m1=thema.getText();
       String m2=themau.getText();
       String m3=theloai.getSelectedItem().toString();
       String m5=thesocanhhoa.getText();
        String m6=thesohoacon.getText();
    for(int i=0;i< model_table.getRowCount();i++){
        for(int j=0;j<7;j++){
            if(m0.equals(mangtam[i][0]))
            { if(m1.equals(mangtam[i][1]))
            { if(m2.equals(mangtam[i][2]))
            {  if(m5.equals(mangtam[i][5]))
            { if(m6.equals(mangtam[i][6]))
            {
           
                
                
                k=1;
                z=i;
            }}}}
    }}}
        System.out.println(k);
        if(k==1){
            String a=(String) table_1.getValueAt(z,4);
            String b=thesoluong.getText();
            int c= Integer. parseInt(a)+ Integer. parseInt(b);
            
            table_1.setValueAt(String.valueOf(c) ,z , 4);
            xoa();
        }   
        else if(k==0){
            hamnhapdl();}
        
            
            
            
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void nutphieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nutphieunhapMouseClicked
      viewnhapp.setVisible(false);
      viewxuatt.setVisible(false);
      viewbang.setVisible(false);
      viewbangxuat.setVisible(false);
      viewbangnhap.setVisible(true);
    }//GEN-LAST:event_nutphieunhapMouseClicked

    private void nutphieuxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nutphieuxuatMouseClicked
      viewnhapp.setVisible(false);
      viewxuatt.setVisible(false);
      viewbang.setVisible(false);
      viewbangnhap.setVisible(false);
      viewbangxuat.setVisible(true);
    }//GEN-LAST:event_nutphieuxuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel nutannhap;
    private javax.swing.JLabel nutphieunhap;
    private javax.swing.JLabel nutphieuxuat;
    private javax.swing.JLabel nutxuatsp;
    private javax.swing.JTable phieunhap;
    private javax.swing.JTable phieuxuat;
    private javax.swing.JTable table_1;
    private javax.swing.JComboBox<String> theloai;
    private javax.swing.JTextField thema;
    private javax.swing.JTextField themau;
    private javax.swing.JTextField thesocanhhoa;
    private javax.swing.JTextField thesohoacon;
    private javax.swing.JTextField thesoluong;
    private javax.swing.JTextField theten;
    private javax.swing.JPanel viewbang;
    private javax.swing.JPanel viewbangnhap;
    private javax.swing.JPanel viewbangxuat;
    private javax.swing.JPanel viewnhapp;
    private javax.swing.JPanel viewxuatt;
    // End of variables declaration//GEN-END:variables

    private static class ArrayLIst {

        public ArrayLIst() {
        }
    }
}
